### ISSUE TITLE
Create a 1.x release?

### ISSUE THREAD

**Issue by mjschultz** [glasslion/redlock#5]
There have been a [handful](https://github.com/glasslion/redlock/compare/f447f0ab5653fea99a04bfa607d55032f195dcf7...master) of changes since the 1.0.0 release that would be nice to have in PyPI.

I'm not sure if they warrant a minor release or a patch release, but either way it would be helpful!

Thanks!

**Comment by glasslion** [comment]
Thanks. I have released 1.1.0.
