### ISSUE TITLE
Error in Python 2.7

### ISSUE THREAD

**Issue by svan1** [glasslion/redlock#8]
The following code results in a runtime error

from redlock import RedLock

lock = RedLock("distributed_lock")
lock.acquire()
print "Hello"
lock.release()

The error is :

....
    lock = RedLock("distributed_lock")
  File "build\bdist.win32\egg\redlock\lock.py", line 98, in __init__
TypeError: type object argument after ** must be a mapping, not str

I think the initialization of connection_details should have a bracket as follows.

        if connection_details is None:
            connection_details = [{
                'host': ' localhost',
                'port': 6379,
                'db': 0,
            }]

**Comment by glasslion** [comment]
I can not reproduce this bug. Could you pls provide more details about your environment?

**Comment by svan1** [comment]
I have Windows7 Professional 64-bit and Python 2.7


C:\Projects\Python\redlocktest>cat simple.py
from redlock import RedLock

lock = RedLock("distributed_lock")
lock.acquire()
print "Hello"
lock.release()
C:\Projects\Python\redlocktest>./simple.py
'.' is not recognized as an internal or external command,
operable program or batch file.

C:\Projects\Python\redlocktest>simple.py
Traceback (most recent call last):
  File "C:\Projects\Python\redlocktest\simple.py", line 3, in <module>
    lock = RedLock("distributed_lock")
  File "build\bdist.win32\egg\redlock\lock.py", line 98, in __init__
TypeError: type object argument after ** must be a mapping, not str

C:\Projects\Python\redlocktest>python --version
Python 2.7.6

C:\Projects\Python\redlocktest>


I hope that helps.
